### ISSUE TITLE
Avoid flashing on initial load

### ISSUE THREAD

**Issue by NunoSempere** [QURIresearch/metaforecast#14]
Behavior: On initial site load, the site flashes. That is, the content is briefly shown, then it disappears, and then it's shown again.

Desired behavior: That doesn't happen.

You can see a video of this behavior on: https://imgur.com/a/hN50EhG

Steps to reproduce: Load a page you haven't searched for before on an incognito tab on Chrome.

**Comment by berekuk** [comment]
Oh. Looks like an issue with the way I used `useEffect`, it reloaded data on initial render.

Fixed with the custom [useNoInitialEffect](https://github.com/berekuk/metaforecast-backend/blob/d921885f1bb24376a93c59c56f6fde4ab1344e10/src/web/search/CommonDisplay.tsx#L47).

I also threw in nprogress bar, hope you'll like it :)

**Comment by berekuk** [comment]
Also, turns out I forgot to add [shallow: true](https://nextjs.org/docs/routing/shallow-routing) option to `router.replace` call, which caused double fetching (Next.js refetches getServerSideProps on navigation by default). Fixed this one too.

**Comment by NunoSempere** [comment]
Great, thanks!!
