### ISSUE TITLE
x-risk database forecasts gone missing in frontend

### ISSUE THREAD

**Issue by NunoSempere** [QURIresearch/metaforecast#39]
E.g., try searching for something in https://docs.google.com/spreadsheets/d/1W10B6NJjicD8O0STPiT3tNV3oFnT8YsfjmtYR8RO_RI/edit#gid=0

**Comment by berekuk** [comment]
Hmm. Is this spreadsheet the primary source of the data? How it got into `xrisk-questions.json`? I see `process-forecasts-from-xrisk`, but it just transforms one JSON file into another, and the file currently committed to the repo seems like its output.

There's also `process-forecasts-from-old-xrisk`, but it takes yet another JSON file (`xrisk-questions-raw.json`) as input.

I ran `manualSendToDb` on my local db with `input/xrisk-questions.json` from the repo, and it works, though I worry that the output misses ids.

(I also lost givewellopenphil from prod for a short period due to me not being careful and running the code from #34, but everything is fixed now).

**Comment by NunoSempere** [comment]
So if I remember correctly, the `xrisk-questions.json` and the `givewell json` were generated using a few scripts, and then I went through it manually to change, e.g., "I" to the correct referent. So the canonical form would be the one on the database.

Separately, I'm restoring the database from a backup.

**Comment by NunoSempere** [comment]
Fixed now. https://metaforecast.org/?query=x-risk+estimates
