### ISSUE TITLE
Api not working

### ISSUE THREAD

**Issue by NunoSempere** [QURIresearch/metaforecast#46]
Right now, https://metaforecast.org/api/questions returns 

```
{
  "errorMessage": "Response payload size exceeded maximum allowed payload size (6291556 bytes).",
  "errorType": "Function.ResponseSizeTooLarge"
}
```

My guess is that this issue is kinda unavoidable, because the api fetches stuff on the server side. I'm thinking we might want to go back to api.metaforecast.org. Not sure how using graphql changes this.

**Comment by berekuk** [comment]
Huh.

Opinions:
- any API needs some limits; if graphql wasn't coming (I hope to finish the first iteration by the end of next week), I'd propose to just implement some kind of pagination
- I can add a pager anyway if there are any users of this API route, it's not a big deal; should I do this?
- on api.metaforecast.org: separate domain seems like an implementation detail to me which would be better to hide from the users; I'd still prefer to stay with /api for this reason if possible (and also to avoid CORS-related issues)

How urgent is this? I'd like to figure out #44 first, since one of its outcomes might be "let's just leave Netlify".

**Comment by NunoSempere** [comment]
This is not really urgent, and a bit moot with the coming graphql

- Separate domain doesn't seem like an implementation detail. In particular, irrc, calls through the /api route are fetched server side in nextjs, which means that we can't exceed the netlify/vercel limits.

**Comment by berekuk** [comment]
> Separate domain doesn't seem like an implementation detail

I meant "an implementation detail for the end user" (our infrastructure decisions shouldn't affect the urls, otherwise users would have to switch if we change our setup), but I'm nitpicking, sorry.

I still believe that paging + Vercel (#52) would solve all our current pains and I'd prefer to avoid a separate DO-hosted domain if possible. In particular, branch preview urls for API might be useful in the future, since APIs and React code often change in lockstep.

**Comment by berekuk** [comment]
`/api/questions` is no more, API consumers should use [GraphQL `questions` query](https://metaforecast.org/api/graphql?query=%7B%0A++questions%28first%3A+100%29+%7B%0A++++pageInfo+%7B%0A++++++hasNextPage%0A++++++endCursor%0A++++%7D%0A++++edges+%7B%0A++++++node+%7B%0A++++++++id%0A++++++++title%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D) which implements paging.
