### ISSUE TITLE
Star rating filter not working as expected

### ISSUE THREAD

**Issue by javipus** [QURIresearch/metaforecast#99]
Filtering by star rating misbehaves when I use quotes in the search term.

Example:

- `https://metaforecast.org/?query=%22lab+leak%22&starsThreshold=1` shows no results
- `https://metaforecast.org/?query=%22lab+leak%22&starsThreshold=3` shows 5 results (all 3 stars, all Metaculus)
- `https://metaforecast.org/?query=%22lab+leak%22&starsThreshold=4` shows one result (4 stars, Rootclaim)

**Comment by NunoSempere** [comment]
Ok, I'm looking into this. I am setting this as "won't fix", because 

- it's relatively easy to try different search terms, e.g., COVID lab leak, 
- it would require too much effort on my part.

However, note that metaforecast is open source, so if you are very motivated by this issue, we accept pull requests
